---
# tasks file for cpan
# Refs: https://github.com/miyagawa/cpanminus/issues/493
- name: Ensure perl-core installed
  yum: name=perl-core state=present

# Install CPANm
- name: Ensure gcc installed
  yum:  name=gcc state=present

- name: Test for cpanm
  shell: perl -MApp::cpanminus -e1
  register: result
  ignore_errors: true

# ToDo:  [WARNING]: Consider using get_url or uri module rather than running curl
- name:  Install CPANm
  shell: curl -L http://cpanmin.us | perl - App::cpanminus
  when:  result|failed

- name: add cpanm symbolic link to /usr/bin/
  file: src=/usr/local/bin/cpanm
        dest=/usr/bin/cpanm
        state=link

- name: Ensure required Perl modules installed
  yum: name={{ item }} state=present
  with_items:
    - perl-Test-Harness
    - perl-Time-HiRes