---
# tasks file for mariadb
- name: install mariadb
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb

- name: install MySQL-python for Ansible
  yum: name=MySQL-python state=installed

- name: turn on mariadb
  service: name=mariadb state=started enabled=yes