---
# tasks file for movabletype6

# Install CPAN module for MT
- name: Install CPAN modules
  cpanm: name={{ item }}
  with_items:
    - CGI
    - Image::Size
    - File::Spec
    - CGI::Cookie
    - LWP::UserAgent
    - parent
    - DBI
    - DBD::mysql

# Put MT source
- name: install unzip
  yum: name=unzip state=present

- name: Put MT source code
  unarchive: src=MT-6.2.4.zip dest=/tmp owner=vagrant group=apache

# ToDo: 冪等性
- name: move to static directory
  command: mv /tmp/MT-6.2.4/mt-static /var/www/html/mt-static

# ToDo: 冪等性
- name: move to application directory
  command: mv /tmp/MT-6.2.4 /var/www/cgi-bin/mt

- name: Create mt-config.cgi
  template: src=templates/mt-config.cgi.j2 dest=/var/www/cgi-bin/mt/mt-config.cgi

- name: set permission for application directory
  file: path={{ item }} mode=0755
  with_fileglob:
    - /var/www/cgi-bin/mt/*.cgi

- name: set permission for blog directory
  file: path=/var/www/html mode=0777

- name: set permission for mt-static
  file: path=/var/www/html/mt-static/support mode=0777

# Create DB
- name: create DB
  mysql_db: name=mt_db state=present collation=utf8_general_ci encoding=utf8

- name: create Users
  mysql_user: name=mt password=1234qwer priv=mt_db.*:ALL state=present

- name: Add apache conf
  template: src=templates/mt.conf.j2 dest=/etc/httpd/conf.d/mt.conf