---
# tasks file for movabletype6

# Install CPAN module for MT
- name: Install CPAN modules
  cpanm: name={{ item }}
  with_items:
    - CGI
    - Image::Size
    - File::Spec
    - CGI::Cookie
    - LWP::UserAgent
    - parent
    - DBI
    - DBD::mysql

# Put MT source
- name: install unzip
  yum: name=unzip state=present

- name: Put MT source code
  unarchive: src={{ mt_source_path }} dest=/tmp owner=vagrant group=apache list_files=yes
  register: ret

- set_fact: mt_tmp_path=/tmp/{{ ret.files[0] }}


- file: path={{ mt_static_dir }} state=absent
# ToDo: 冪等性
- name: move to static directory
  command: mv {{ mt_tmp_path }}mt-static {{ mt_static_dir }}

- file: path={{ mt_application_dir }} state=absent
# ToDo: 冪等性
- name: move to application directory
  command: mv {{ mt_tmp_path }} {{ mt_application_dir }}

- name: Create mt-config.cgi
  template: src=templates/mt-config.cgi.j2 dest={{ mt_application_dir }}/mt-config.cgi

- name: set permission for application directory
  file: path={{ item }} mode=0755
  with_fileglob:
    - "{{ mt_application_dir }}/*.cgi"

- name: set permission for blog directory
  file: path={{ mt_website_dir }} mode=0777

- name: set permission for mt-static
  file: path={{ mt_static_dir }}/support mode=0777

# Create DB
- name: create DB
  mysql_db: name={{ mt_db_name }} state=present collation=utf8_general_ci encoding=utf8

- name: create Users
  mysql_user: name={{ mt_db_user_name }} password={{ mt_db_user_password }} priv={{ mt_db_name }}.*:ALL state=present

- name: Add apache conf
  template: src=templates/mt.conf.j2 dest=/etc/httpd/conf.d/mt.conf